# Services
services:
    aws_ses:
        class: SimpleEmailService
        arguments:
            - %aws_ses.access_key%
            - %aws_ses.secret_key%
            - %aws_ses.region_endpoint%
